// EDIT: Add your friends' messages here.
// photo: path relative to public/ (e.g. 'inbox/yy.jpg'), or null for text-only

export const MESSAGES = [
  {
    id: 0,
    from: 'katie',
    emoji: '📌',
    message: '',
    photo: null,
    pinned: true,
  },
  {
    id: 1,
    from: 'karina',
    emoji: '💌',
    message: `To my lovely Ariel,\n\nHappy happy birthday!!! Today, on your special day, I hope you are reminded of how loved you are by all those around you! I am so lucky to have met you through KUT and developed such a wonderful friendship with you. Ever since I joined, I always admired you as such a great leader, dancer, and just an amazing friend. Your warmth, caring nature, and love are always such a comfort to be around. I miss seeing you all the time, making funny tik toks, dancing together, and visiting lots of yummy food spots. Hopefully we will see each other super soon and our funny shenanigans can commence again. Let's have more adventures like the zoo and Pizza Kaiju! With that said, I'm wishing you another year of nothing but success in LA! I can't wait to see you soon, whether it be SD, LA, or anywhere in between :)) I love you so so much!\n\nKarina`,
    photo: 'inbox/karina.jpg',
  },
  {
    id: 2,
    from: 'misa',
    emoji: '💌',
    message: `dear ariel chan,\n\nhappy happy 23rd birthday pookie <3 i am so grateful to have met you last year in kut with what was one of the happiness moments of my life 🥹 in all honesty, i was a little bit intimidated at first because of how gorgeous you were on library walk when i first saw u recruiting (like I felt blinded bahaha 🤣 ), but now i know that on top of all that you are also such a kind, sweet, and softspoken person with boundless creativity—your creative vision with kut always amazed me!!!!\n\ndance connected us, but now as friends, i wish you a year full of love, happiness, brand sponsorships, and non-toxic work ppl <3 i miss you dearly, but i know all of us will always find a way to see each other again. i cannot wait to see where this year takes u!!\n\nxoxo,\nmisa`,
    photos: ['inbox/misa1.jpg', 'inbox/misa2.jpg'],
  },
  {
    id: 3,
    from: 'camilla',
    emoji: '💌',
    message: `Hi Ariel! Happy birthday 🥳\nIt's so crazy to think we've known each other since first year and stayed in KUT all four years together! I always loved being in your pieces, and I feel like I learned so much from you.\nAlso, congratulations on starting your new job!! Wishing you all the best in this new chapter 🫶`,
    photo: null,
  },
  {
    id: 4,
    from: 'amanda c.',
    emoji: '💌',
    message: `hey ariel! happy happy birthday!! i wish you an amazing birthday, miss you lots and i hope to see you again soon < 3`,
    photo: 'inbox/amandac.png',
  },
  {
    id: 5,
    from: 'jonny',
    emoji: '💌',
    message: 'HAPPY BIRTHDAY ARIEL, i hope you have an amazing day and im so glad to have met ya and see you and katie blossom! YALL DA BEST THANK YOU HAVE AN AWESOME ONE ILL BUY YOU A BOBA SOMETIME FOR YOUR BDAY!',
    photo: 'inbox/jonny.jpg',
  },
  {
    id: 6,
    from: 'kaylinn',
    emoji: '💌',
    message: `嗨囉Ariel！！祝你23歲生日快樂～\n好久不見了很想你喔😻好想趕快21跟你們去趴踢哈哈哈哈 等我合法一定要約我去😭\n好久沒有跟你跳舞跟你玩了😔畢業後你感覺變得好忙 但希望你工作什麼的都可以順順利利！之後去LA玩一定會去找你～也等你多多回來SD找我們🫶🏻（或是總有一天我們會在台灣見到嗎`,
    photo: 'inbox/kaylinn.jpg',
  },
  {
    id: 7,
    from: 'natalie',
    emoji: '💌',
    message: `hi ariel!!\n\nhappiest of birthdays to you 🎂  I am wishing you lots of happiness and joy on this special day! I feel like I know you pretty decently just from how often katie tells me about you HEHE (ofc its all good things :>). Even though we aren't too close, I know anyone close to katie is someone I will get along with! Hope we can see each other and hang out more in the future, byebye for neow\n\n-natalie 💗`,
    photo: 'inbox/natalie.jpg',
  },
  {
    id: 8,
    from: 'kyrsten',
    emoji: '💌',
    message: `HAPPY BIRTHDAY ARIEL!!!!! :3  I hope you are having the best day ever rn hehe^^ I hope you know I miss you every time I walk into practice or I happen to see anything cat related and I wish we could still dance together every week ;-; when you and Katie came down to teach the dance workshop in spring quarter I was so happy to see you both and was sad I couldn't hang out more (gomen I think I was busy/had to go home ;-;) but next time you're back here I will try to make time to hang out!! I know I tell you this all the time haha but if you EVER need a car ride anywhere in San Diego or anything in general while you're here I'll always be here for whatever you need/I will be your free uber driver >:) I love you so much though and again I hope you have an amazing day and I miss you and omg yayayayaya HAPPY BIRTHDAY <3333 😄   - Kyrsten :3`,
    photo: null,
    photos: ['inbox/kyrsten1.jpg', 'inbox/kyrsten2.jpg', 'inbox/kyrsten3.jpg'],
    photoLayout: 'one-right-two-below',
  },
  {
    id: 9,
    from: 'steven',
    emoji: '💌',
    message: `HAPPY BIRTHDAY ARIELLL,\n\nI hope you have been enjoying the postgrad life away from the vis arts department (save me) hehe. It's very fun to see you every now and then whenever I play roblox or you come down. I kind of only play roblox now whenever SMAK decides to play LOL but I love. Cheers to more years to come and I hope I can still see what you've been up to YAA.\n\n"君と僕 はじめまして" (from a tws song :3)\n- steven`,
    photo: 'inbox/steven.png',
  },
  {
    id: 12,
    from: 'mia/nancy',
    emoji: '💌',
    message: `happy birthday ariel! u r supa talented and kind and i love playing roblox with u :-) i hope to see u back in sj soon so we can have more matcha parties (*´꒳\`*)  -mia\n\nhappy 23(???)!!! come serenade us piano again~~~~\ni found a salt bread place here if you want to try😈😈😈\nwish u the happiest and healthiest\n-nancy`,
    photo: 'inbox/mia_and_nancy.jpg',
  },
  {
    id: 10,
    from: 'ellyse',
    emoji: '💌',
    message: `HAPPY BIRTHDAY ARIELL!!!!!!! miss u so so much hope you're doing well in la :3 thank you for being an amazing friend and im so grateful we got to be part of each others life in college, could not imagine college without u ! cant believe its been more than half a year since we graduated & we're turning 23 this year ahHHHHHH T.T I still remember meeting you when we were both 19/20 and now we're working adults njkfnfj.. anyways, thank you for being the reason I even discovered kut, i will forever remember the first time meeting you in person after watching ur videos IM FOREVER UR OG FAN hehe!! dont forget to remind yourself that you're doing amazing even on hard days bc ur spectacularrrr 😄\n\nwishing you the happiest of birthdays and a year filled with happiness ahead ❤️ 天天开心 !!`,
    photo: 'inbox/ellyse.jpg',
  },
  {
    id: 13,
    from: 'amanda z.',
    emoji: '💌',
    message: `hai ariel!!! happy birthday fellow aries! have a great great bday and i hope u get to have lots of yummy food and that you are doing well in your new position! glad to have met you through kut and wishing you a happy 23!`,
    photo: null,
  },
  {
    id: 14,
    from: 'zach',
    emoji: '💌',
    message: `Happy Birthday Ariel It's been forever but I hope you've been doing well! I'm wishing you another year of success and continuing to gift the world with your talent 🎊`,
    photo: 'inbox/zach.jpg',
  },
  {
    id: 15,
    from: 'bri',
    emoji: '💌',
    message: `HAPPY BIRTHDAY ARIEL !! 🩷🖤🩷\noh girl don't get me started… how i miss the days we'd all come together at nathan's apartment to eat spicy noodles, drink together, make silly tiktoks, and then go clubbing :,) i will forever hold those moments so close to my heart, and they wouldn't have been nearly as fun and silly without you there. i miss you being in san diego queen, but im so excited to see what this new era brings you in LA! we may be a little spread out now, but just know you'll always have your biggest cheerleaders (besides katie) in both the bay AND in san diego !! ٠࣪⭑\n\naries diva, i hope your day is as beautiful as you are\n- bri bri <3`,
    photo: 'inbox/bri.jpg',
  },
  {
    id: 17,
    from: 'elvis',
    emoji: '💌',
    message: `Happy birthday arielle!! I hope you have a wonderful birthday and u a silly goober. Congrats on passing your drivers licenses test too! We need to eat haidilao more together :). Stay safe and have fun with Katie and byebye`,
    photo: 'inbox/elvis.jpg',
  },
  {
    id: 16,
    from: 'zoe dang',
    emoji: '💌',
    message: `Hoiii ariellll! I know our meeting was brief but I wanted to letchu know I had a great time. I hope to see you soon and happy birthday!!!! 🥳`,
    photo: null,
  },
  {
    id: 11,
    from: 'brandon/darren',
    emoji: '💌',
    message: `hai Ariel :D\nI just wanted to wish you an amazing 23rd birthday. I hope that life is treating you well and i also hope that we'll see each other around! Even though we have not conversed directly, my impression of you is that you're soooooooo cool like you have that certain je ne sais quoi... like you're THAT GIRLLL. Wishing you the best and happy birthday! - Brandon :3\n\nhappy birthday ariel!!!! wishing you the best and hope your day is fill of happiness and joy :D - darren`,
    photo: 'inbox/brandon.png',
  },
]
